export enum Permission {
  CREATE_TODO = "CREATE_TODO",
  UPDATE_TODO = "UPDATE_TODO",
  DELETE_TODO = "DELETE_TODO",
  COMPLETE_TODO = "COMPLETE_TODO",

  INVITE_COLLABORATOR = "INVITE_COLLABORATOR",
  REMOVE_COLLABORATOR = "REMOVE_COLLABORATOR",
  CHANGE_ROLE = "CHANGE_ROLE",

  DELETE_PROJECT = "DELETE_PROJECT",
}
